<a href="https://colab.research.google.com/github/miso-20/statistic_programing_2/blob/main/6_1)_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
- Pandas는 데이터를 처리하고 분석하기 위해 사용하는 Python 패키지로, 주로 DataFrame이라는 2차원 데이터 구조를 다룬다.
- Excel, CSV, 텍스트 파일 등 다양한 형태의 데이터를 읽고, 정리하고, 분석에 필요한 형태로 변환하는 과정을 Data Handling이라고 한다.
- Pandas는 이러한 Data Handling을 수행하기 위한 다양한 기능을 제공한다.
- 참고 : https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html

In [ ]:
import pandas as pd

## 1. Dataframe(데이터 프레임)
- DataFrame의 행(row)과 열(column)은 각각 다음과 같은 특징을 가진다.
    - 행(row): 하나의 관측 대상(observation)에 대한 정보를 나타낸다.
    - 열(column): 하나의 변수(variable) 또는 특성(characteristic)에 대한 정보를 나타내며, 일반적으로 동일한 자료형의 값들로 구성된다.
    - 하나의 column에 숫자들이 있지만, 문자로 인식한다. ex) "1,000" -> format 개념
- 각 행에는 이를 구분하는 `인덱스(index)`가 있으며, 각 열에는 `열 이름(column name)`이 있다.
- 인덱스와 열 이름에는 숫자나 문자 등을 사용할 수 있다.

### 1-1) DataFrame 정의
- DataFrame은 pd.DataFrame()을 이용하여 생성할 수 있다.
- 아래 코드는 5명의 이름, 성별, 나이, 키를 저장한 DataFrame을 생성하는 예제이다.

In [ ]:
df = pd.DataFrame(
    { 'name' : ['이철수', '김영희', '홍길동', 'John Smith', 'Mary Doe'],
      'sex'  : ['M', 'F', 'M', 'M', 'F'],
      'age'  : [ 23, 25, 21, 33, 45],
      'height' : [153.5, 175.3, 163.4, 180.0, 165.7]
    } )

print(df)
print(type(df))

         name sex  age  height
0         이철수   M   23   153.5
1         김영희   F   25   175.3
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0
4    Mary Doe   F   45   165.7
<class 'pandas.DataFrame'>

- DataFrame을 생성하는 방법 중 하나는 `dictionary`를 이용하는 것이다.
    - Dictionary의 key는 열 이름(column name), value는 해당 열에 저장되는 값들을 나타낸다.
    - 예를 들어 'name': ['이철수', '김영희', '홍길동', 'John Smith', 'Mary Doe']는 name이라는 열을 생성하고, 5명의 이름을 저장한다.
- Dictionary에서 각 항목은 쉼표(,)로 구분한다.
- `type`함수를 이용하여 확인해보면, pandas의 DataFrame 객체임을 알 수 있다.

### 1-2) Indexing 및 Slicing
- DataFrame에서도 NumPy 배열과 마찬가지로 Indexing과 Slicing을 이용하여 원하는 데이터를 선택할 수 있다.
- DataFrame에서는 다음과 같은 방법으로 데이터를 선택할 수 있다.
    - `열 이름(column name)`을 이용하여 특정 열을 선택한다.        ## slicing
    - `loc` method를 이용하여 행과 열의 이름을 기준으로 선택한다.  ## slicing
    - `iloc` method를 이용하여 행과 열의 위치를 기준으로 선택한다. ## indexing
- Boolean filtering 이용하여 조건을 만족하는 데이터를 선택한다. 이때, `[]` 또는 `loc` method를 이용한다.

In [ ]:
print(df["name"], '\n')
print(df.name)

0           이철수
1           김영희
2           홍길동
3    John Smith
4      Mary Doe
Name: name, dtype: str

0           이철수
1           김영희
2           홍길동
3    John Smith
4      Mary Doe
Name: name, dtype: str

- df.종가(원)가 아니라 df["종가(원)"] 으로 써야 인식됨

In [ ]:
sub_df = df[["name", "sex"]]
print(sub_df)

         name sex
0         이철수   M
1         김영희   F
2         홍길동   M
3  John Smith   M
4    Mary Doe   F

In [ ]:
df[["name", "sex"]]

         name sex
0         이철수   M
1         김영희   F
2         홍길동   M
3  John Smith   M
4    Mary Doe   F

In [ ]:
df[df['height'] <= 165]

  name sex  age  height
0  이철수   M   23   153.5
2  홍길동   M   21   163.4

In [ ]:
print(df['sex'] == 'M')
print((df['height'] >= 160.0))
print((df['sex'] == 'M') & (df['height'] >= 160.0))

0     True
1    False
2     True
3     True
4    False
Name: sex, dtype: bool
0    False
1     True
2     True
3     True
4     True
Name: height, dtype: bool
0    False
1    False
2     True
3     True
4    False
dtype: bool

In [ ]:
df[(df['sex'] == 'M') & (df['height'] >= 160.0)]

         name sex  age  height
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0

In [ ]:
df.loc[(df['height'] >= 170.0) , 'name']

1           김영희
3    John Smith
Name: name, dtype: str

In [ ]:
df.loc[ (df['sex'] == 'M') , ['name', 'height']]

         name  height
0         이철수   153.5
2         홍길동   163.4
3  John Smith   180.0

In [ ]:
df.iloc[0,0]

'이철수'

In [ ]:
df.iloc[3,1:3] # 이름 빼고 / 성별,나이,이름 가져옴

sex     M
age    33
Name: 3, dtype: object

In [ ]:
df.iloc[0,:]

name        이철수
sex           M
age          23
height    153.5
Name: 0, dtype: object

### 1-3) Series
- `DataFrame`을 구성하는 하나의 row, column은 `Series`란 반환되는 경우가 있다.

In [ ]:
print(df.name)
print(type(df.name))

0           이철수
1           김영희
2           홍길동
3    John Smith
4      Mary Doe
Name: name, dtype: str
<class 'pandas.Series'>

In [ ]:
print(df.iloc[0, :])
print(type(df.iloc[0, :]))

name        이철수
sex           M
age          23
height    153.5
Name: 0, dtype: object
<class 'pandas.Series'>

## 2. 외부 데이터 읽기
- 실제 분석에 사용되는 데이터는 주로 CSV, Excel, 텍스트 파일 등의 형태로 저장되어 있다.
- Pandas에서는 read_csv(), read_excel() 등의 함수를 이용하여 외부 데이터를 DataFrame으로 불러올 수 있다.
### 2-1) Work directory 지정
- 데이터를 읽기 전, 데이터의 위치(path)를 코드에 입력시켜야 한다.
- `os` 모듈을 이용하여 `path`를 지정하여 파일의 위치 및 파일을 지정하여 읽어들일 수 있다.
- `os.getcwd()` : 현재 환경에 대한 `path`를 보여준다.

In [ ]:
import os
os.getcwd()

'C:\\Users\\98mij\\OneDrive\\바탕 화면\\김미소\\통계프로그래밍2'

- `os.chdir(x)`: 환경에 대한 `path`를 변경시켜 준다. 이때, 위치를 표현할때 `\\` 또는 `/`를 이용해야 한다.

In [ ]:
os.chdir("C:/Users/98mij/OneDrive/바탕 화면/김미소/통계프로그래밍2") # chdir: change directory 약자
os.getcwd()

'C:\\Users\\98mij\\OneDrive\\바탕 화면\\김미소\\통계프로그래밍2'

### 2-2) Excel 파일 읽기
- pd.read_excel()을 이용하여 Excel 파일을 읽어보자.
- 주가 데이터들이 저장된 `예제데이터.xlsx` 파일을 사용한다.

In [ ]:
kospi_dat = pd.read_excel("예제데이터.xlsx")

- 데이터의 앞부분과 뒷부분, 전체 구조를 확인할 때는 `head()`, `tail()`, `infor()`를 이용한다.

In [ ]:
print(kospi_dat.head(), '\n')
print(kospi_dat.tail(), '\n')
print(kospi_dat.info())

          날짜  삼성전자_종가  삼성전자_거래량  NAVER_종가  NAVER_거래량      코스피  코스피200
0 2012-01-02  1080000    263300    209000      79684  1826.37  238.70
1 2012-01-03  1105000    339046    219500     129258  1875.41  245.82
2 2012-01-04  1080000    342389    219500     114888  1866.22  244.24
3 2012-01-05  1055000    346691    216500     122556  1863.74  243.56
4 2012-01-06  1040000    376753    216500     118049  1843.14  240.57

             날짜  삼성전자_종가  삼성전자_거래량  NAVER_종가  NAVER_거래량      코스피  코스피200
2724 2023-01-25    63400  16822710    202000     988822  2428.57  320.76
2725 2023-01-26    63900  13278277    204000     873219  2468.65  325.57
2726 2023-01-27    64600  18760182    211500    1212987  2484.02  327.98
2727 2023-01-30    63300  20995234    207000    1204050  2450.47  322.67
2728 2023-01-31    61000  29746731    202500    1076468  2425.08  317.26

<class 'pandas.DataFrame'>
RangeIndex: 2729 entries, 0 to 2728
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   날짜         2729 non-null   datetime64[us]
 1   삼성전자_종가    2729 non-null   int64
 2   삼성전자_거래량   2729 non-null   int64
 3   NAVER_종가   2729 non-null   int64
 4   NAVER_거래량  2729 non-null   int64
 5   코스피        2729 non-null   float64
 6   코스피200     2729 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(4)
memory usage: 149.4 KB
None

- `NAVER_종가`에 대해 `220000`원을 넘는 날짜를 확인해보자.

In [ ]:
sub_dat = kospi_dat[(kospi_dat.NAVER_종가 > 220000)]

- kospi_dat하고 '(kospi_dat.NAVER_종가 > 220000)' 조건의 길이가 같기 때문에, 돌아간다.

In [ ]:
print(sub_dat.iloc[0, :])

날짜           2012-01-12 00:00:00
삼성전자_종가                  1028000
삼성전자_거래량                  371462
NAVER_종가                  222000
NAVER_거래량                 130738
코스피                      1864.57
코스피200                    243.46
Name: 8, dtype: object

- NAVER_종가가 220000을 넘는 첫 번째 날짜 ********

## 3. 외부 데이터로 저장
- 위에서 생성한 데이터를 Excel 파일(.xlsx)로 저장해보자
- excel데이터로 저장하기 위해서는 `to_excel` method를 이용한다.
    - index option : excel로 저장할때, row index를 같이 저장하는 옵션이다. default는 True이다.

In [ ]:
os.getcwd() # 파일 어디로 가는지 지정하고 저장해라

'C:\\Users\\98mij\\OneDrive\\바탕 화면\\김미소\\통계프로그래밍2'

In [ ]:
sub_dat.to_excel("네이버_out.xlsx", index = False)